version: '2'
services:
  fess:
    image: codelibs/fess:11.4.1
    restart: always
    ports:
      - "8080:8080"
    environment:
      ES_HTTP_URL: "http://elasticsearch:9200"
      ES_TRANSPORT_URL: "elasticsearch:9300"
      FESS_DICTIONARY_PATH: "/var/lib/elasticsearch/config/"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esconfig:/usr/share/elasticsearch/config
volumes:
  esdata:
    driver: local
  esconfig:
    driver: local

