USE Kikan
GO
;
DROP PROCEDURE IF EXISTS P_MONTHLY_SALES_LOG;
GO
;
CREATE PROCEDURE P_MONTHLY_SALES_LOG (@P_DATE AS date) AS
BEGIN
WITH UH AS (
SELECT * FROM URIAGE_SHIIRE_HD WHERE URIAGE_DATE BETWEEN DATEADD(DAY, 1, EOMONTH(@P_DATE, -1)) AND EOMONTH(@P_DATE, 0)
UNION
SELECT * FROM DEL_URIAGE_SHIIRE_HD WHERE URIAGE_DATE BETWEEN DATEADD(DAY, 1, EOMONTH(@P_DATE, -1)) AND EOMONTH(@P_DATE, 0)
), UM AS (
SELECT * FROM URIAGE_SHIIRE_MEI
UNION
SELECT * FROM DEL_URIAGE_SHIIRE_MEI
), KK AS (
SELECT * FROM KOTEI_KANRI
UNION
SELECT * FROM DEL_KOTEI_KANRI
), KM AS (
SELECT * FROM KOTEI_MEISAI
UNION
SELECT * FROM DEL_KOTEI_MEISAI
)
SELECT UH.EIGYOSHO_CD AS [営業所CD]
     , COALESCE(H_TORIHIKISAKI.TORIHIKISAKI_CD, 0) AS [販売先CD]
     , COALESCE(H_TORIHIKISAKI.TORIHIKISAKI_NM, N'') AS [販売先名]
     , COALESCE(M_USER.USER_ID, 0) AS [担当者CD]
     , COALESCE(M_USER.TANTO_NM, N'') AS [担当者名]
     , COALESCE(M_HANBAISAKI.EIGYO_CHIKU_CD, 0) AS [地区CD]
     , COALESCE(M_EIGYO_CHIKU.CHIKU_NM, N'') AS [地区名]
     , CONVERT(nvarchar, UH.SHUKKA_DATE, 111) AS [出荷日]
     , CONVERT(nvarchar, UH.URIAGE_DATE, 111) AS [売上日]
     , CONVERT(nvarchar, KK.SEIKYU_HAKKO_DT, 111) AS [請求日]
     , M_HANBAISAKI.SHIME_NITTEI AS [締日]
     , UH.SHIKIBETSU_KBN AS [処理識別区分]
     , CONVERT(nvarchar, UH.JUCHU_DENPYO_NO)
       + CONVERT(nvarchar, UH.KOTEI_KANRI_NO)
       + CONVERT(nvarchar, UH.KOTEI_KANRI_AKAKURO_NO) AS [受注伝票NO]
     , UH.KOTEI_KANRI_NO AS [枝番1]
     , UH.KOTEI_KANRI_AKAKURO_NO AS [枝番2]
     , UM.URIAGE_SHIIRE_MEI_GYO_NO AS [売上仕入明細行NO]
     , UM.KOTEI_CD AS [工程CD]
     , UM.KIKAKU_CD AS [規格CD]
     , KI.KIKAKU_KBN AS [規格区分]
     , KI.KIKAKU_NM AS [規格名]
     , COALESCE(J.JOTAI_CD, 0) AS [状態CD]
     , COALESCE(J.JOTAI_NM, N'') AS [状態名]
     , KM.KODO_CD AS [硬度CD]
     , KM.KODO_HANI AS [硬度範囲]
     , COALESCE(K.KEIJO_CD, 0) AS [形状CD]
     , COALESCE(K.KANA_KANJI_KBN, N'') AS [形状_カナ漢字区分]
     , COALESCE(K.KANA_NM, N'') AS [形状_カナ名称]
     , COALESCE(K.KANJI_NM, N'') AS [形状_漢字名称]
     , UM.SUNPO1 AS [寸法1]
     , UM.SUNPO2 AS [寸法2]
     , UM.SUNPO3 AS [寸法3]
     , UM.SUNPO4 AS [寸法4]
     , UM.SUNPO5 AS [寸法5]
     , KM.ANA_KEI AS [穴径]
     , KM.ANA_TOMARI AS [穴止まり]
     , KM.TEIJAKU_KBN AS [定尺区分]
     , KM.ZUMEN_NO AS [図面番号]
     , UM.HYOJI_SUNPO AS [表示寸法]
     , UM.URIAGE_INZU AS [売上員数]
     , UM.URISHI_URIAGE_TNK_KBN AS [売上単価区分]
     , UM.URIAGE_JURYO_NYURYOKU AS [売上重量入力]
     , UM.URIAGE_TNK AS [売上単価]
     , UM.URIAGE_KN AS [売上金額]
     , UM.URIAGE_ZEI_KN AS [売上税額]
     , COALESCE(S_TORIHIKISAKI.TORIHIKISAKI_CD, 0) AS [仕入先CD]
     , COALESCE(S_TORIHIKISAKI.TORIHIKISAKI_NM, N'') AS [仕入先名]
     , CONVERT(nvarchar, UM.SHIIRE_DATE, 111) AS [仕入日]
     , CONVERT(nvarchar, KM.SHIIRE_SHIME_DATE, 111) AS [仕入締日]
     , UM.URISHI_SHIIRE_TNK_KBN AS [仕入単価区分]
     , UM.SHIIRE_TNK AS [仕入単価]
     , UM.SHIIRE_KN AS [仕入金額]
     , UM.SHIIRE_ZEI_KN AS [仕入税額]
     , UH.ZAIRYO_KN AS [材料費]
     , UH.NETSUKAKO_KN AS [熱処理費]
     , UH.HYOMENKAKO_KN AS [表面加工費]
     , UH.JISHA_KAKO_KN AS [自加工費]
     , UH.JISHA_ANAAKE_KN AS [自穴開費]
     , UH.JISHA_SONOTA_KN AS [自その他]
     , UH.GAI_KAKO_KN AS [外加工費]
     , UH.GAI_ANAAKE_KN AS [外穴開費]
     , UH.GAI_SONOTA_KN AS [外その他]
     , UH.SO_RIEKI_KN AS [総利益額]
     , UH.SETSUDAN_KN AS [切断費]
     , UH.NIATSUKAI_KN AS [荷扱費]
     , UH.KINRI_KN AS [金利]
     , UH.JISHITEN_SETSUDAN_KN AS [自店切断]
     , UH.JISHITEN_NIATSUKAI_KN AS [自店荷扱]
     , UM.NOKOHA_KN AS [鋸刃代]
     , UM.URI_SHOGO_EIGYOSHO_CD AS [売上照合営業所CD]
     , KM.SHIIRE_KANKATSU_SOKO_CD AS [倉庫CD]
     , UM.KIKAI_KBN AS [機械区分]
     , UM.MACHINE_CD AS [機械CD]
     , COALESCE(C1.URIAGE_CHARGE_NO, N'') AS [売上チャージNO1]
     , COALESCE(C1.URIAGE_INZU, 0) AS [売上員数1]
     , COALESCE(C2.URIAGE_CHARGE_NO, N'') AS [売上チャージNO2]
     , COALESCE(C2.URIAGE_INZU, 0) AS [売上員数2]
     , COALESCE(C3.URIAGE_CHARGE_NO, N'') AS [売上チャージNO3]
     , COALESCE(C3.URIAGE_INZU, 0) AS [売上員数3]
     , COALESCE(C4.URIAGE_CHARGE_NO, N'') AS [売上チャージNO4]
     , COALESCE(C4.URIAGE_INZU, 0) AS [売上員数4]
     , COALESCE(C5.URIAGE_CHARGE_NO, N'') AS [売上チャージNO5]
     , COALESCE(C5.URIAGE_INZU, 0) AS [売上員数5]
     , COALESCE(C6.URIAGE_CHARGE_NO, N'') AS [売上チャージNO6]
     , COALESCE(C6.URIAGE_INZU, 0) AS [売上員数6]
     , COALESCE(C7.URIAGE_CHARGE_NO, N'') AS [売上チャージNO7]
     , COALESCE(C7.URIAGE_INZU, 0) AS [売上員数7]
     , COALESCE(C8.URIAGE_CHARGE_NO, N'') AS [売上チャージNO8]
     , COALESCE(C8.URIAGE_INZU, 0) AS [売上員数8]
     , COALESCE(C9.URIAGE_CHARGE_NO, N'') AS [売上チャージNO9]
     , COALESCE(C9.URIAGE_INZU, 0) AS [売上員数9]
     , COALESCE(C10.URIAGE_CHARGE_NO, N'') AS [売上チャージNO10]
     , COALESCE(C10.URIAGE_INZU, 0) AS [売上員数10]
     , REPLACE(KK.URIAGE_BIKO, CHAR(13) + CHAR(10), N'|') AS [売上備考]
     , REPLACE(KK.SHANAI_SHIJI, CHAR(13) + CHAR(10), N'|') AS [社内指示]
     , REPLACE(KK.SHIIRE_SHIJI, CHAR(13) + CHAR(10), N'|') AS [仕入先指示]
     , REPLACE(KK.BUTSURYU_SHIJI, CHAR(13) + CHAR(10), N'|') AS [物流指示]
     , KM.SHANAI_MEMO AS [社内メモ]
FROM UH
JOIN UM ON UH.KOTEI_KANRI_ID = UM.KOTEI_KANRI_ID
JOIN KK ON UH.KOTEI_KANRI_ID = KK.ID
JOIN KM ON UM.KOTEI_KANRI_ID = KM.KOTEI_KANRI_ID AND UM.KOTEI_MEISAI_NO = KM.KOTEI_MEISAI_NO AND UM.KOTEI_MEISAI_AKAKURO_NO = KM.KOTEI_MEISAI_AKAKURO_NO
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C1 ON UM.KOTEI_KANRI_ID = C1.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C1.URIAGE_SHIIRE_MEI_GYO_NO AND C1.CHARGE_MEI_NO = 1
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C2 ON UM.KOTEI_KANRI_ID = C2.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C2.URIAGE_SHIIRE_MEI_GYO_NO AND C2.CHARGE_MEI_NO = 2
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C3 ON UM.KOTEI_KANRI_ID = C3.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C3.URIAGE_SHIIRE_MEI_GYO_NO AND C3.CHARGE_MEI_NO = 3
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C4 ON UM.KOTEI_KANRI_ID = C4.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C4.URIAGE_SHIIRE_MEI_GYO_NO AND C4.CHARGE_MEI_NO = 4
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C5 ON UM.KOTEI_KANRI_ID = C5.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C5.URIAGE_SHIIRE_MEI_GYO_NO AND C5.CHARGE_MEI_NO = 5
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C6 ON UM.KOTEI_KANRI_ID = C6.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C6.URIAGE_SHIIRE_MEI_GYO_NO AND C6.CHARGE_MEI_NO = 6
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C7 ON UM.KOTEI_KANRI_ID = C7.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C7.URIAGE_SHIIRE_MEI_GYO_NO AND C7.CHARGE_MEI_NO = 7
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C8 ON UM.KOTEI_KANRI_ID = C8.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C8.URIAGE_SHIIRE_MEI_GYO_NO AND C8.CHARGE_MEI_NO = 8
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C9 ON UM.KOTEI_KANRI_ID = C9.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C9.URIAGE_SHIIRE_MEI_GYO_NO AND C9.CHARGE_MEI_NO = 9
LEFT JOIN URIAGE_SHIIRE_CHARGE_MEI AS C10 ON UM.KOTEI_KANRI_ID = C10.KOTEI_KANRI_ID AND UM.URIAGE_SHIIRE_MEI_GYO_NO = C10.URIAGE_SHIIRE_MEI_GYO_NO AND C10.CHARGE_MEI_NO = 10
LEFT JOIN M_JOTAI AS J ON UM.JOTAI_CD = J.JOTAI_CD
LEFT JOIN M_KIKAKU AS KI ON UM.KIKAKU_CD = KI.KIKAKU_CD
LEFT JOIN M_KEIJO AS K ON UM.KEIJO_CD = K.KEIJO_CD
LEFT JOIN M_HANBAISAKI ON UH.HANBAISAKI_NAIBU_CD = M_HANBAISAKI.HANBAISAKI_NAIBU_CD
LEFT JOIN M_TORIHIKISAKI AS H_TORIHIKISAKI ON M_HANBAISAKI.TORIHIKISAKI_NAIBU_CD = H_TORIHIKISAKI.TORIHIKISAKI_NAIBU_CD
LEFT JOIN M_TORIHIKISAKI AS S_TORIHIKISAKI ON UM.SHIIRESAKI_NAIBU_CD = S_TORIHIKISAKI.TORIHIKISAKI_NAIBU_CD
LEFT JOIN M_USER ON UH.TANTO_USER_CD1 = M_USER.USER_CD
LEFT JOIN M_EIGYO_CHIKU ON M_HANBAISAKI.EIGYOSHO_CD = M_EIGYO_CHIKU.EIGYOSHO_CD AND M_HANBAISAKI.EIGYO_CHIKU_CD = M_EIGYO_CHIKU.EIGYO_CHIKU_CD
ORDER BY UH.EIGYOSHO_CD
       , UH.SHUKKA_DATE
       , H_TORIHIKISAKI.TORIHIKISAKI_CD
       , CONVERT(nvarchar, UH.JUCHU_DENPYO_NO) + CONVERT(nvarchar, UH.KOTEI_KANRI_NO) + CONVERT(nvarchar, UH.KOTEI_KANRI_AKAKURO_NO)
       , UM.URIAGE_SHIIRE_MEI_GYO_NO
END
