USE [BUNSEKI]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER OFF
GO
;
CREATE PROCEDURE [dbo].[P_MONTHLY_SALES_LOG] (@P_DATE AS date) AS
BEGIN
SELECT [営業所CD]
     , [販売先CD]
     , NULL AS [販売先名]
     , [担当者CD]
     , NULL AS [担当者名]
     , NULL AS [地区CD]
     , NULL AS [地区名]
     , CONCAT(LEFT(STR([出荷日], 8, 0), 4), '-', SUBSTRING(STR([出荷日], 8, 0), 5, 2), '-', RIGHT(STR([出荷日], 8, 0), 2)) AS [出荷日]
     , IIF([売上日]=0, NULL, CONCAT(LEFT(STR([売上日], 8, 0), 4), '-', SUBSTRING(STR([売上日], 8, 0), 5, 2), '-', RIGHT(STR([売上日], 8, 0), 2))) AS [売上日]
     , NULL AS [請求日]
     , NULL AS [締日]
     , [処理識別] AS [処理識別区分]
     , [伝票枝NO] AS [受注伝票NO]
     , [枝番1]
     , [枝番2]
     , [行NO] AS [売上仕入明細行NO]
     , [工程CD]
     , [規格] AS [規格CD]
     , NULL AS [規格区分]
     , [規格] AS [規格名]
     , [状態名] AS [状態CD]
     , [状態名]
     , NULL AS [硬度CD]
     , NULL AS [硬度範囲]
     , NULL AS [形状CD]
     , NULL AS [形状_カナ漢字区分]
     , NULL AS [形状_カナ名称]
     , [漢字名称] AS [形状_漢字名称]
     , [寸法1]
     , [寸法2]
     , [寸法3]
     , NULL AS [寸法4]
     , NULL AS [寸法5]
     , NULL AS [穴径]
     , NULL AS [穴止まり]
     , NULL AS [定尺区分]
     , NULL AS [図面番号]
     , [表示寸法]
     , [員数] AS [売上員数]
     , [売上単価区分]
     , [売上重量入力]
     , [売上単価]
     , [売上金額]
     , NULL AS [売上税額]
     , [仕入先CD]
     , NULL AS [仕入先名]
     , IIF([仕入日]=0, NULL, CONCAT(LEFT(STR([仕入日], 8, 0), 4), '-', SUBSTRING(STR([仕入日], 8, 0), 5, 2), '-', RIGHT(STR([仕入日], 8, 0), 2))) AS [仕入日]
     , NULL AS [仕入締日]
     , [仕入単価区分]
     , [仕入単価]
     , [仕入金額]
     , NULL AS [仕入税額]
     , [材料費]
     , [熱処理費]
     , [表面処理] AS [表面加工費]
     , [自加工費]
     , [自穴空費] AS [自穴開費]
     , [自その他]
     , [外加工費]
     , [外穴空費] AS [外穴開費]
     , [外その他]
     , [総利益] AS [総利益額]
     , NULL AS [切断費]
     , NULL AS [荷扱費]
     , NULL AS [金利]
     , NULL AS [自店切断]
     , NULL AS [自店荷扱]
     , NULL AS [鋸刃代]
     , NULL AS [売上照合営業所CD]
     , [倉庫CD]
     , NULL AS [機械区分]
     , [鋸盤CD] AS [機械CD]
     , [チャージNO1] AS [売上チャージNO1]
     , [員数1] AS [売上員数1]
     , [チャージNO2] AS [売上チャージNO2]
     , [員数2] AS [売上員数2]
     , [チャージNO3] AS [売上チャージNO3]
     , [員数3] AS [売上員数3]
     , NULL AS [売上チャージNO4]
     , NULL AS [売上員数4]
     , NULL AS [売上チャージNO5]
     , NULL AS [売上員数5]
     , NULL AS [売上チャージNO6]
     , NULL AS [売上員数6]
     , NULL AS [売上チャージNO7]
     , NULL AS [売上員数7]
     , NULL AS [売上チャージNO8]
     , NULL AS [売上員数8]
     , NULL AS [売上チャージNO9]
     , NULL AS [売上員数9]
     , NULL AS [売上チャージNO10]
     , NULL AS [売上員数10]
     , [備考] AS [売上備考]
     , NULL AS [社内指示]
     , NULL AS [仕入先指示]
     , NULL AS [物流指示]
     , NULL AS [社内メモ]
FROM [BUNSEKI].[dbo].[売上仕入]
WHERE CAST((IIF([売上日]=0, CONCAT(LEFT(STR([出荷日], 8, 0), 4), '-', SUBSTRING(STR([出荷日], 8, 0), 5, 2), '-', RIGHT(STR([出荷日], 8, 0), 2))
          , CONCAT(LEFT(STR([売上日], 8, 0), 4), '-', SUBSTRING(STR([売上日], 8, 0), 5, 2), '-', RIGHT(STR([売上日], 8, 0), 2)))) AS DATE)
	  BETWEEN DATEADD(DAY, 1, EOMONTH(@P_DATE, -1)) AND EOMONTH(@P_DATE, 0)
ORDER BY [営業所CD], [出荷日], [販売先CD], [伝票枝NO], [枝番1], [枝番2], [行NO]
END

GO

